### ISSUE TITLE
Newsletter Template page - XML Delivery Status column

### ISSUE THREAD

**Issue by psantori** [contactlab/contactlab-magento-connect#1]
The XML Delivery status column gets hardly readable after a certain (even small) number of deliveries. A separate page should be linked and status details logs should be moved to the newly created page.

![newsletter templates newsletter magento admin](https://cloud.githubusercontent.com/assets/100616/8979037/6f3eed7c-36a7-11e5-87a9-ff22ff353d7d.png)

**Comment by NikLabWriter** [comment]
Hello,

I think I've found the solution to your problem at last, read it here please <http://spunoquigi.sickbuddies.com/xyqcwxw>

Very truly yours, Barton Nik
