### ISSUE TITLE
Export Subscribers - Missing value in the XML file

### ISSUE THREAD

**Issue by pasuslab** [contactlab/contactlab-magento-connect#3]
In the subscribers XML file the CREATED_AT tag is empty, regardless of the contents of the field on the table.

**Comment by markino79** [comment]
Nella classe Contactlab_Subscribers_Model_Exporter_Subscribers 
abbiamo trovato un piccolo problema:

nella funzione _fillStoreAttributes nell'istruzione:

$store = $this->stores[$item->getData('store_id')];

riceviamo un notice di indice non definito .

La funzione sembra che al suo interno non gestisca la situazione:

$store = $this->stores[$item->getData('store_id')];
foreach (array('store_id', 'store_name', 'website_id', 'website_name',
    'group_id', 'group_name', 'lang') as $k) {
    $toFill[$k] = $store[$k];
}

Per evitare i notices (davvero tanti sull'ordine delle decine di migliaia)  ho messo in testa alla funzione.

if (!isset($this->stores[$item->getData('store_id')])){
    return;
}

vien da se che i dati che dovrebbe estrarre dallo store non vengono estratti.

**Comment by NicolaClab** [comment]
Grazie Marco, abbiamo preso in carico la segnalazione e con la prossima versione, porporremo una soluzione a questa richiesta.
