### ISSUE TITLE
Problema notice invasivo

### ISSUE THREAD

**Issue by markino79** [contactlab/contactlab-magento-connect#8]
Nella classe Contactlab_Subscribers_Model_Exporter_Subscribers 
abbiamo trovato un piccolo problema:

nella funzione _fillStoreAttributes nell'istruzione:

$store = $this->stores[$item->getData('store_id')];

riceviamo un notice di indice non definito .

La funzione sembra che al suo interno non gestisca la situazione:

$store = $this->stores[$item->getData('store_id')];
foreach (array('store_id', 'store_name', 'website_id', 'website_name',
'group_id', 'group_name', 'lang') as $k) {
$toFill[$k] = $store[$k];
}

Per evitare i notices (davvero tanti sull'ordine delle decine di migliaia) ho messo in testa alla funzione.

if (!isset($this->stores[$item->getData('store_id')])){
return;
}

vien da se che i dati che dovrebbe estrarre dallo store non vengono estratti.

**Comment by NicolaClab** [comment]
Closed in 2.4.1
